name: gpth
description: 'Tool to help you with exporting stuff from Google Photos'
version: 3.3.1
homepage: 'https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.3
  mime: ^1.0.4
  collection: ^1.17.0
  convert: ^3.1.1
  fuzzysearch: ^0.1.3
  crypto: ^3.0.2
  exif: ^3.1.2
  console_bars: ^1.1.0
  file_picker_desktop: ^1.1.1
  archive: ^3.3.5
  proper_filesize: ^0.0.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
